### ISSUE TITLE
How to get channel ID's after running matchy.py

### ISSUE THREAD

**Issue by arjunchandra2** [ChaseC99/matchy#5]
Hello! 

I recently ran the `matchy.py` script to create matchings and I noticed that the channel ID's were printed as the groups were created. However, I did not note these channel ID's down anywhere and I am wanting to send a reminder message using the `send_group_reminder_message(group_ids: [str], message=reminder_message)` function but I am not sure how to obtain the channel/group ID's now?

Any help would be appreciated!

**Comment by ell-ml** [comment]
Hiiii! 

Re: channel ID - I'm unsure if you'd have the perms for it but you can get the Slack channel ID from right-clicking a channel > View Channel Details and scrolling to the bottom for the channel ID 
![image](https://github.com/user-attachments/assets/7c5665b0-faa6-40ed-97d4-0380f937787c)

Hope this helps!

**Comment by arjunchandra2** [comment]
Thank youuuuu
